### PR TITLE
R u still working?

### PR DESCRIPTION
**Pull request by ZambrOvosky**
If yes, I want to help u, but idk how. Tell what I need to know and to do.
Knowledge languages: **C, C++, C#, Java and others**.

_PS: I never have programmed for games._

### CODE REVIEW

**Comment by ZambrOvosky** [comment]
Sorry, wrong way

**Comment by Mitgenosse** [comment]
Hello @JvDelicia 
no I am not playing the game anymore.

**Comment by Override92** [comment]
Hi @JvDelicia 
It is very hard for me to understand the existing source code. 
Also I dont know if there is any possibility to synchronize roads, buildings, ...
I also don't play this game at the moment. But I think it would be nice to play with friends together.

**Comment by ZambrOvosky** [comment]
@Override92 
> Yes, for me too.
> Idk exactly, but if it's possible, it's will be so hard.
> I stopped playing cause SP it's boring. I really only play MP games.

**Pull request closed without merging**
